In [1]:
%pip install numpy
import numpy as np



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


# Case Study

## Q - You are working with sales data for a small store. The data includes the number of items sold on each day for a month (30 days), and you have the sales data for 3 items: apples, oranges, and bananas. The sales data is represented as a 2D NumPy array, where each row represents a day, and each column represents the sales data for an item.

### 1. Creating the Data: How would you create a NumPy array representing the sales data for 30 days and 3 items, with random sales values between 0 and 100?

In [10]:
data = np.random.randint(0, 100, size=(30, 3))
data

array([[85, 78, 12],
       [58, 76, 86],
       [26, 53, 69],
       [40,  2, 11],
       [64,  8, 90],
       [84, 97, 91],
       [ 0, 50,  5],
       [86, 34, 89],
       [79, 32, 16],
       [12, 14, 67],
       [21, 29, 48],
       [17, 86, 81],
       [69, 60, 15],
       [40, 59, 65],
       [29, 35, 50],
       [52, 86, 92],
       [21, 89,  3],
       [71, 90, 10],
       [53, 24, 51],
       [51, 96, 72],
       [59, 22, 34],
       [46, 88, 72],
       [10, 98, 83],
       [98, 29, 90],
       [95, 48, 19],
       [80, 24, 88],
       [82, 75, 57],
       [17, 34, 69],
       [82,  1, 90],
       [51, 56, 57]])

### 2. Total Sales for Each Item: Write the NumPy code to calculate the total sales for each item over the 30 days.

In [11]:
np.sum(data, axis=0)

array([1578, 1573, 1682])

## 3.  Average Sales for Each Item: Write the NumPy code to calculate the average sales for each item over the 30 days.

In [12]:
np.mean(data, axis=0)

array([52.6       , 52.43333333, 56.06666667])

## 4. Find Maximum Sales Day for Each Item: Write the NumPy code to find the day with the maximum sales for each item.


In [13]:
np.max(data, axis=0), np.min(data, axis=0)

(array([98, 98, 92]), array([0, 1, 3]))

## Q - You are analyzing the grades of 5 students in 3 subjects: Math, Science, and English. The grades are stored in a 2D NumPy array, where each row represents a student and each column represents a subject.

### 1. Create the Grades Array: How would you create a NumPy array to represent the grades of 5 students in 3 subjects?

In [22]:
data = np.random.randint(1, 100, size=(5, 3))
data

array([[58, 23, 72],
       [49, 13, 89],
       [66, 12, 22],
       [ 7, 31, 65],
       [36, 65, 34]])

### 2. Find the Average Grade for Each Student: Write the NumPy code to calculate the average grade for each student.

In [15]:
np.mean(data, axis=1)

array([61.66666667, 41.66666667, 65.33333333, 54.        , 55.66666667])

### 3.  Find the Highest Grade in Each Subject: Write the NumPy code to find the highest grade in each subject.

In [16]:
np.max(data, axis=0)

array([65, 92, 98])

### 4.  Find the Student with the Highest Total Grade: Write the NumPy code to find the student with the highest total grade across all subjects.


In [17]:
mean = np.mean(data, axis=1)
np.argmax(mean)

2

## Q - You are working with temperature data for a week (7 days). You have temperatures for two cities, City A and City B.

### 1. Create the Temperature Array: How would you create a NumPy array to represent the temperatures for 7 days in 2 cities?

In [23]:
data = np.random.randint(0, 100, size=(7, 2))
data

array([[29, 23],
       [63,  1],
       [58, 63],
       [ 3, 75],
       [64, 76],
       [10, 95],
       [25, 52]])

### 2. Find the Average Temperature for Each Day: Write the NumPy code to calculate the average temperature for each day across the two cities.

In [24]:
np.mean(data, axis=1)

array([26. , 32. , 60.5, 39. , 70. , 52.5, 38.5])

### 3. Find the Highest Temperature Recorded: Write the NumPy code to find the highest temperature recorded across both cities.

In [25]:
np.max(data, axis=0)

array([64, 95])

### 4. Find the City with the Highest Average Temperature: Write the NumPy code to find which city had the highest average temperature.

In [30]:
mean = np.mean(data, axis=0)
np.argmax(mean, axis=0)

1

# Extra Questions

## 1. How to replace items that satisfy a condition with another value in numpy array?

In [35]:
arr = np.arange(10) 
arr[arr%2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## 2. How to replace items that satisfy a condition without affecting the original array?

In [36]:
arr = np.arange(10) 
out = arr.copy() 
out[out%2 == 1] = -1 
print('Modified Array',out) 
print('\nOriginal Array',arr)

Modified Array [ 0 -1  2 -1  4 -1  6 -1  8 -1]

Original Array [0 1 2 3 4 5 6 7 8 9]


## 3. Get the positions of top 5 maximum values in a given array

In [50]:
a = np.random.uniform(low=1, high=50, size=(20)) 
print('Array', a)
sort = a.argsort() 
print('Sorted Index', sort)
print('Positions', sort[-5:][::-1])
print('Values', a[sort][-5:][::-1])

Array [17.62415838 15.91731895 17.48917493 31.84659687 48.77145888 33.75084065
 40.13903061  6.11373453 34.93786905 26.09240504 28.32250937 16.30041799
 29.88251735 41.72555683 12.41707198 28.02202166 13.74290509 13.63801478
 41.24623605 17.82927903]
Sorted Index [ 7 14 17 16  1 11  2  0 19  9 15 10 12  3  5  8  6 18 13  4]
Positions [ 4 13 18  6  8]
Values [48.77145888 41.72555683 41.24623605 40.13903061 34.93786905]


## 4. Convert array_of_arrays into a flat linear 1d

In [ ]:
arr1 = np.arange(3) 
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
arr_2d = np.concatenate([arr1, arr2, arr3]) 
print(arr_2d)

[0 1 2 3 4 5 6 7 8 9]


## 5. You have the following dataset with some missing (NaN) values.

In [62]:
data = np.array([10.5, 12.3, np.nan, 14.2, np.nan, 13.7])
data.size

6

In [61]:
# How many missing values are there?
data[np.isnan(data)].size

2

In [63]:
# Replace NaNs with the mean of the non-NaN values?
data_not_nan = data[~np.isnan(data)]
mean = np.mean(data_not_nan)
data[np.isnan(data)] = mean
data

array([10.5  , 12.3  , 12.675, 14.2  , 12.675, 13.7  ])